import Head from 'next/head';

import Navbar from '../components/Navbar';
import Banner from '../components/Banner';
import Results from '../components/Results';
import { getRandom } from '../utils/characterGen';

const Home = ({ drinks }) => {
  return (
    <div>
      <Head>
        <title>Cocktails - Ken</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Banner />
      <Results drinks={drinks} />
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  const url = process.env.API_URL;
  const array = ['a', 'v', 'k', 'm', 's', 'b', 'r'];
  const searchTerm = getRandom(array);

  const request = await fetch(`${url}${searchTerm}`);
  const { drinks } = await request.json();

  return {
    props: {
      drinks,
    },
  };
}
